package fastock.fastock.Utils;

public enum EnumPrivilegios {
    //PRODUCTO
    ROLE_PRODUCTO_CREATE_UPDATE,
    ROLE_PRODUCTO_SELECT,
    PRODUCTO_DELETE,
    //INSUMO
    INSUMO_CREATE_UPDATE,
    INSUMO_SELECT,
    INSUMO_DELETE,
    //FABRICACION
    FABRICACION_CREATE_UPDATE,
    FABRICACION_SELECT,
    FABRICACION_DELETE,
    //USUARIO
    USUARIO_CREATE_UPDATE,
    USUARIO_SELECT,
    USUARIO_DELETE,
    //EMPRESA
    EMPRESA_CREATE_UPDATE,
    EMPRESA_SELECT,
    EMPRESA_DELETE,
    //INVENTARIOS
    INVENTARIOS_CREATE_UPDATE,
    INVENTARIOS_SELECT,
    INVENTARIOS_DELETE

}
